name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List files in working directory
        run: |
          pwd
          ls -la
          find . -type f
          if [ ! -d "minecraft-backup-tool" ]; then echo "Error: minecraft-backup-tool folder not found!"; exit 1; fi
          cd minecraft-backup-tool
          pwd
          ls -la
          if [ ! -f "build.py" ]; then echo "Error: build.py not found!"; exit 1; fi
          if [ ! -f "main.py" ]; then echo "Error: main.py not found!"; exit 1; fi
          if [ ! -d "resources" ]; then echo "Error: resources folder not found!"; exit 1; fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: minecraft-backup-tool
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Build the app
        working-directory: minecraft-backup-tool
        run: |
          python build.py

      - name: Fix executable permissions
        working-directory: minecraft-backup-tool
        run: |
          chmod +x dist/MinecraftBackupTool.app/Contents/MacOS/MinecraftBackupTool
          ls -la dist/MinecraftBackupTool.app/Contents/MacOS/

      - name: Check if app exists
        working-directory: minecraft-backup-tool
        run: |
          ls -la dist/
          if [ ! -d "dist/MinecraftBackupTool.app" ]; then
            echo "Error: dist/MinecraftBackupTool.app does not exist!"
            exit 1
          fi

      - name: Create ZIP
        working-directory: minecraft-backup-tool
        run: |
          mkdir output
          zip -r output/MinecraftBackupTool.app.zip dist/MinecraftBackupTool.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftBackupTool-macOS
          path: minecraft-backup-tool/output/MinecraftBackupTool.app.zip
