name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # ¡Clave aquí!

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build the app
        run: |
          python build.py

      - name: Create ZIP
        run: |
          mkdir output
          zip -r output/MinecraftBackupTool.app.zip dist/MinecraftBackupTool.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MinecraftBackupTool-macOS
          path: output/MinecraftBackupTool.app.zip
