name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Build the app
        run: |
          python build.py

      - name: Check if app exists
        run: |
          ls -la dist/
          if [ ! -d "dist/MinecraftBackupTool.app" ]; then
            echo "Error: dist/MinecraftBackupTool.app does not exist!"
            exit 1
          fi

      - name: Create ZIP
        run: |
          mkdir output
          zip -r output/MinecraftBackupTool.app.zip dist/MinecraftBackupTool.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftBackupTool-macOS
          path: output/MinecraftBackupTool.app.zip
